### ISSUE TITLE
Generate custom framework bundles from source

### ISSUE THREAD

**Issue by bulenttastan** [MovedNetwork/op-move#27]
### Description
Sui framework only the packages `move-stdlib` at `0x21` and `sui-framework` at `0x22`.
Aptos framework modules needs a little more editing so there won't be referencing to unused modules.

The goal is to rely on existing framework modules without copying them over to this crate.

### Tasks
- [ ]  Create a genesis crate to build and generate `sui.mrb` and `aptos.mrb` files
- [ ] Use these files correctly from the `genesis.rs`
- [ ] Assign Aptos natives address to `0x11`, `0x12`... etc

### Notes
Some of the work has started here: https://github.com/MovedNetwork/framework/pull/1
But ideally we want this code to be part of the `op-move` repo. Then we can delete the `framework` repo altogether.

We will have instructions to use `0x11`, `0x12` addresses instead of `0x1`, `0x2` for dApp builders.
Sui native addresses will be already set correctly in https://github.com/MovedNetwork/op-move/issues/28

- op-move will switch to use Rust workspace (existing code will be one crate in the workspace)
- New crate for generating framework release bundle (possible two -- one for Aptos and one for Sui)
- Generating the release bundle must not change any Move source code to reduce maintenance burden on us
- The release bundle generation can modify Move.toml to change the target address
- The release bundle generation should be pegged to a specific release version of Aptos/Sui (this can be done by having them as git submodules or by cloning as needed)
