### ISSUE TITLE
Inject Sui natives when creating the Move VM execution instance

### ISSUE THREAD

**Issue by bulenttastan** [MovedNetwork/op-move#28]
### Description
The Sui framework modules are already added, but they are missing the native functions in the VM. Similar work is already done for Aptos, but Sui native functions are missing.

### Tasks
- [ ] Convert Sui native function table to run on Aptos Move VM
- [ ] Inject the native functions and test in the same `natives` test contract
- [ ] Assign natives address to `0x21` for move-stdlib and `0x22` for sui-framework

### Notes
This is probably harder than it looks, unless we find a clever way of doing it. Because the `NativeFunctionTable` types have the same name, but they are different dependencies coming from their corresponding internal cargo packages.

Make sure the addresses are not left at default values, but set to `0x21` and `0x22`.
